/**
 * Stage 2 — 元件設計與元件間通訊（TypeScript 版）
 * 對應官方文件：https://vuejs.org/guide/components/registration
 */
import type { ExerciseMeta } from '../types'

export const stage02Exercises: ExerciseMeta[] = [
  {
    id: 'q01',
    title: 'defineProps 定義與型別驗證',
    difficulty: 1,
    types: ['填空', '找錯誤'],
    docUrl: 'https://vuejs.org/guide/components/props',
    docSection: 'Props',
    component: () => import('./q01-props/Starter.vue'),
    answer: () => import('./q01-props/Answer.vue'),
  },
  {
    id: 'q02',
    title: 'defineEmits 事件宣告與觸發',
    difficulty: 1,
    types: ['從零撰寫'],
    docUrl: 'https://vuejs.org/guide/components/events',
    docSection: 'Component Events',
    component: () => import('./q02-emits/Starter.vue'),
    answer: () => import('./q02-emits/Answer.vue'),
  },
  {
    id: 'q03',
    title: 'defineModel（Component v-model）',
    difficulty: 2,
    types: ['從零撰寫'],
    docUrl: 'https://vuejs.org/guide/components/v-model',
    docSection: 'Component v-model',
    component: () => import('./q03-define-model/Starter.vue'),
    answer: () => import('./q03-define-model/Answer.vue'),
  },
  {
    id: 'q04',
    title: '預設插槽與具名插槽（Slots）',
    difficulty: 1,
    types: ['填空'],
    docUrl: 'https://vuejs.org/guide/components/slots',
    docSection: 'Slots',
    component: () => import('./q04-slots/Starter.vue'),
    answer: () => import('./q04-slots/Answer.vue'),
  },
  {
    id: 'q05',
    title: 'Scoped Slots（作用域插槽）',
    difficulty: 2,
    types: ['從零撰寫'],
    docUrl: 'https://vuejs.org/guide/components/slots',
    docSection: 'Scoped Slots',
    component: () => import('./q05-scoped-slots/Starter.vue'),
    answer: () => import('./q05-scoped-slots/Answer.vue'),
  },
  {
    id: 'q06',
    title: 'Provide / Inject 依賴注入',
    difficulty: 2,
    types: ['填空', '找錯誤'],
    docUrl: 'https://vuejs.org/guide/components/provide-inject',
    docSection: 'Provide / Inject',
    component: () => import('./q06-provide-inject/Starter.vue'),
    answer: () => import('./q06-provide-inject/Answer.vue'),
  },
  {
    id: 'q07',
    title: 'Fallthrough Attributes',
    difficulty: 2,
    types: ['找錯誤'],
    docUrl: 'https://vuejs.org/guide/components/attrs',
    docSection: 'Fallthrough Attributes',
    component: () => import('./q07-fallthrough/Starter.vue'),
    answer: () => import('./q07-fallthrough/Answer.vue'),
  },
  {
    id: 'q08',
    title: '動態元件（component :is）',
    difficulty: 2,
    types: ['填空'],
    docUrl: 'https://vuejs.org/guide/essentials/component-basics',
    docSection: 'Dynamic Components',
    component: () => import('./q08-dynamic-component/Starter.vue'),
    answer: () => import('./q08-dynamic-component/Answer.vue'),
  },
  {
    id: 'q09',
    title: 'defineAsyncComponent 非同步載入',
    difficulty: 2,
    types: ['從零撰寫'],
    docUrl: 'https://vuejs.org/guide/components/async',
    docSection: 'Async Components',
    component: () => import('./q09-async-component/Starter.vue'),
    answer: () => import('./q09-async-component/Answer.vue'),
  },
  {
    id: 'q99',
    title: '綜合題：可配置 Modal 系統',
    difficulty: 3,
    types: ['功能實作'],
    docUrl: 'https://vuejs.org/guide/components/slots',
    docSection: 'Stage 2 綜合 — Props + Emits + Slots + Provide/Inject',
    component: () => import('./q99-capstone-modal/Starter.vue'),
    answer: () => import('./q99-capstone-modal/Answer.vue'),
  },
]
