/** Stage 3 — Composables 與邏輯複用 */
export const stage03Exercises = [
  { id: 'q01', title: 'Composable 函式設計原則', difficulty: 2, types: ['填空', '重構'],
    docUrl: 'https://vuejs.org/guide/reusability/composables', docSection: 'Composables',
    component: () => import('./q01-composable-basics/Starter.vue'),
    answer: () => import('./q01-composable-basics/Answer.vue') },
  { id: 'q02', title: '響應式參數傳遞（toValue / MaybeRef）', difficulty: 2, types: ['從零撰寫'],
    docUrl: 'https://vuejs.org/guide/reusability/composables', docSection: 'Composables — toValue()',
    component: () => import('./q02-to-value/Starter.vue'),
    answer: () => import('./q02-to-value/Answer.vue') },
  { id: 'q03', title: '非同步 Composable（useFetch pattern）', difficulty: 2, types: ['功能實作'],
    docUrl: 'https://vuejs.org/guide/reusability/composables', docSection: 'Async State Example',
    component: () => import('./q03-use-fetch/Starter.vue'),
    answer: () => import('./q03-use-fetch/Answer.vue') },
  { id: 'q04', title: 'Composable 與 Lifecycle 整合', difficulty: 2, types: ['填空'],
    docUrl: 'https://vuejs.org/guide/reusability/composables', docSection: 'Composables — Lifecycle Hooks',
    component: () => import('./q04-composable-lifecycle/Starter.vue'),
    answer: () => import('./q04-composable-lifecycle/Answer.vue') },
  { id: 'q05', title: 'Custom Directives（自訂指令）', difficulty: 2, types: ['從零撰寫'],
    docUrl: 'https://vuejs.org/guide/reusability/custom-directives', docSection: 'Custom Directives',
    component: () => import('./q05-custom-directives/Starter.vue'),
    answer: () => import('./q05-custom-directives/Answer.vue') },
  { id: 'q06', title: 'Plugin 開發與安裝', difficulty: 2, types: ['填空'],
    docUrl: 'https://vuejs.org/guide/reusability/plugins', docSection: 'Plugins',
    component: () => import('./q06-plugins/Starter.vue'),
    answer: () => import('./q06-plugins/Answer.vue') },
  { id: 'q99', title: '綜合題：useLocalStorage + useDebouncedRef', difficulty: 3, types: ['功能實作'],
    docUrl: 'https://vuejs.org/guide/reusability/composables', docSection: 'Stage 3 綜合 — 複合 Composable 設計',
    component: () => import('./q99-capstone/Starter.vue'),
    answer: () => import('./q99-capstone/Answer.vue') },
]
