/** Stage 4 — Vue Router 路由管理 */
export const stage04Exercises = [
  { id: 'q01', title: 'createRouter / createWebHistory 基礎設定', difficulty: 1, types: ['填空'],
    docUrl: 'https://router.vuejs.org/guide/', docSection: 'Vue Router — Getting Started',
    component: () => import('./q01-router-setup/Starter.vue'),
    answer: () => import('./q01-router-setup/Answer.vue') },
  { id: 'q02', title: '動態路由參數（:id）與 useRoute', difficulty: 1, types: ['從零撰寫'],
    docUrl: 'https://router.vuejs.org/guide/essentials/dynamic-matching', docSection: 'Dynamic Route Matching',
    component: () => import('./q02-dynamic-params/Starter.vue'),
    answer: () => import('./q02-dynamic-params/Answer.vue') },
  { id: 'q03', title: '巢狀路由（Nested Routes）', difficulty: 2, types: ['填空', '找錯誤'],
    docUrl: 'https://router.vuejs.org/guide/essentials/nested-routes', docSection: 'Nested Routes',
    component: () => import('./q03-nested-routes/Starter.vue'),
    answer: () => import('./q03-nested-routes/Answer.vue') },
  { id: 'q04', title: '導航守衛（beforeEach / beforeEnter）', difficulty: 2, types: ['從零撰寫'],
    docUrl: 'https://router.vuejs.org/guide/advanced/navigation-guards', docSection: 'Navigation Guards',
    component: () => import('./q04-navigation-guards/Starter.vue'),
    answer: () => import('./q04-navigation-guards/Answer.vue') },
  { id: 'q05', title: '路由 Meta 欄位與權限控制', difficulty: 2, types: ['功能實作'],
    docUrl: 'https://router.vuejs.org/guide/advanced/meta', docSection: 'Route Meta Fields',
    component: () => import('./q05-route-meta/Starter.vue'),
    answer: () => import('./q05-route-meta/Answer.vue') },
  { id: 'q06', title: '程式化導航（useRouter）', difficulty: 1, types: ['填空'],
    docUrl: 'https://router.vuejs.org/guide/essentials/navigation', docSection: 'Programmatic Navigation',
    component: () => import('./q06-programmatic-nav/Starter.vue'),
    answer: () => import('./q06-programmatic-nav/Answer.vue') },
  { id: 'q07', title: '路由懶載入（動態 import）', difficulty: 2, types: ['找錯誤', '重構'],
    docUrl: 'https://router.vuejs.org/guide/advanced/lazy-loading', docSection: 'Lazy Loading Routes',
    component: () => import('./q07-lazy-loading/Starter.vue'),
    answer: () => import('./q07-lazy-loading/Answer.vue') },
  { id: 'q08', title: '路由查詢字串（query params）', difficulty: 1, types: ['從零撰寫'],
    docUrl: 'https://router.vuejs.org/guide/essentials/navigation', docSection: 'Query Parameters',
    component: () => import('./q08-query-params/Starter.vue'),
    answer: () => import('./q08-query-params/Answer.vue') },
  { id: 'q99', title: '綜合題：含權限控制的多頁面系統', difficulty: 3, types: ['功能實作'],
    docUrl: 'https://router.vuejs.org/guide/advanced/navigation-guards', docSection: 'Stage 4 綜合 — Router + Guards + Meta',
    component: () => import('./q99-capstone/Starter.vue'),
    answer: () => import('./q99-capstone/Answer.vue') },
]
